name: Sanity checks

on:
  - push
  - pull_request

jobs:
  lint-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3

      - name: Lint
        run: make ci-lint

      - name: Test
        run: make test
